#!/system/bin/sh

#flags every mounted partition as non rotational

MTD=`ls -d /sys/block/mtd*`;
LOOP=`ls -d /sys/block/loop*`;
RAM=`ls -d /sys/block/ram*`;
MMC=`ls -d /sys/block/mmc*`;

for j in $DM $MTD $LOOP $RAM;
do
echo 0 > $j/queue/rotational;
done

echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
echo 512 > /sys/devices/virtual/bdi/31:0/read_ahead_kb;
#echo 512 > /sys/devices/virtual/bdi/31:1/read_ahead_kb;
#echo 512 > /sys/devices/virtual/bdi/31:2/read_ahead_kb;
#echo 512 > /sys/devices/virtual/bdi/31:3/read_ahead_kb;
#echo 512 > /sys/devices/virtual/bdi/31:4/read_ahead_kb;
#echo 512 > /sys/devices/virtual/bdi/31:5/read_ahead_kb;
#echo 512 > /sys/devices/virtual/bdi/31:5/read_ahead_kb;

for i in \
`find /data -iname "*.db"`
do \
sqlite3 $i 'VACUUM;'; 
done
