#!/bin/bash
#
# Squish a otapackage for distribution
# Superatmel y Blerfont (Base Cyanogen)
#

OUT_TARGET_HOST=linux-x86
export VENDOR=vendor/osr
MODS=$VENDOR/mods
OTAPACKAGE=$OUT/$PRODUCT_ROM_FILE-ota.zip
ROMPACKAGE=$OUT/$PRODUCT_ROM_FILE.zip

OPTICHARGER=$ANDROID_BUILD_TOP/$VENDOR/tools/opticharger2
OPTICHARGER_FRAMEWORK=$ANDROID_BUILD_TOP/$VENDOR/tools/opticharger_framework
QUIET=-q
DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
REPACK=$OUT/repack.d
REPACKOTA=$REPACK/ota
updater=$REPACKOTA/META-INF/com/google/android/updater-script

CORES=$( cat /proc/cpuinfo | grep -c processor )

CHANGE_FRAMEWORK=1

. entorno.sh

# Verificación de entorno de desarrollo operativo
if [ -z "$OUT" -o ! -d "$OUT" ]; then
  msgErr "$0 solo funciona con un entorno completo de desarrollo. $OUT debe existir."
  exit 1
fi

# Se verifica que existe el fichero inicial.
if [ ! -f "$OTAPACKAGE" ]; then
  msgErr "$OTAPACKAGE no existe!"
  exit 1
fi

# Configuración del dispositivo
# ALIAS: Nombre corto del dispositivo. Se recomienda no tocar este valor, se toma a partir del nombre del product.
# KERNELMOD: 1 indica que el núcleo tiene módulos sin comprimir. 0 valor por defecto
# SETUP: 1 Indica que no queremos Setupwizard en el arranque.

# Valores por defecto
KERNELMOD=0
SETUP=1
ALIAS=${TARGET_PRODUCT:4}

#Valores específicos
case "$ALIAS" in
    ace)
	KERNELMOD=1
	SETUP=0
        ;;
    anzu)
	KERNELMOD=1
	SETUP=0
        ;;
    galaxysmtd) 
	SETUP=0
	;;
    maguro) 
	SETUP=0
	;;
    pyramid) 
	SETUP=0
	;;
    sirius)
	SETUP=0
	;;
esac

# Elimina cualquier directorio de un trabajo antiguo
clear
msgInfo "Limpiando el entorno..."
rm -rf $REPACK
mkdir -p $REPACK

# Descomprime el otapackage y ejecuta opticharge en todos los apks
mkdir $REPACKOTA

    cd $REPACKOTA
    msgStatus "Desempaquetando $OTAPACKAGE..."
    unzip $QUIET $OTAPACKAGE
  
# Copiado de archivos comunes
    cp -rf $ANDROID_BUILD_TOP/$MODS/common/* $REPACKOTA/

if [ $CHANGE_FRAMEWORK -eq 1 ]
then
# Extraemos el framework para modificarlo
    mkdir $REPACKOTA/system/framework/opticharge
    cd $REPACKOTA/system/framework/opticharge
    msgStatus "Desempaquetando framework-res..."
    unzip -q ../framework-res.apk
  
# Comprimimos sin optimizar pues lo haremos luego 
    msgStatus "Comprimiendo framework..."
    zip -rq framework-res.apk *
    mv -f framework-res.apk ../framework-res.apk
    cd ..
    rm -rf opticharge
else
    msgStatus "No se haran cambios del framework-res"
fi
  
cd $REPACKOTA/system/framework

# Copiado de archivos especificos del dispositivo
    cp -r $ANDROID_BUILD_TOP/$MODS/terminales/$ALIAS/* $REPACKOTA/

# Ejecuta si existe personalizaciones específicas del dispositivo.
if [ -f $ANDROID_BUILD_TOP/$MODS/terminales/$ALIAS/personalizar.sh ]; then
   	$ANDROID_BUILD_TOP/$MODS/terminales/$ALIAS/personalizar.sh $REPACKOTA
  	rm $REPACKOTA/personalizar.sh
fi

# Ejecuta opticharger especial sobre el framework para copiar las imagenes modificadas de la rom dentro de él
$OPTICHARGER framework-res.apk

#Ejecuta opticharger sobre el resto de apks de la rom
cd $REPACKOTA/system/app
find ./ -name \*.apk | xargs --max-args=1 --max-procs=${CORES} $OPTICHARGER

#Si pasa el Opticharger por el LatinIME mata los diccionarios
cp $OUT/system/app/LatinIME.apk $REPACKOTA/system/app/LatinIME.apk

#mv $REPACKOTA/system/app/Stk.apk $REPACKOTA/system/app/Stk.app
mv $REPACKOTA/system/app/Development.apk $REPACKOTA/system/app/Development.app

# Corregir build.prop
sed -i \
  -e '/ro\.kernel\.android\.checkjni/d' \
  -e '/ro\.build\.type/s/eng/user/' \
  -e '/ro\.build\.date\.utc/s/.*/ro.build.date.utc=0/' \
  $REPACKOTA/system/build.prop

# Decidimos si queremos SetupWizard al inicio o no
if [ "$SETUP" -eq 1 ]; then
sed -i 's/ro.setupwizard.mode=OPTIONAL/ro.setupwizard.mode=DISABLED/g' $REPACKOTA/system/build.prop
fi

# Eliminar binarios innecesarios
cd $REPACKOTA/system/bin
$ECHO $DELETE_BINS | xargs rm -f

# Eliminar drivers inalambricos
rm -rf $REPACKOTA/system/lib/modules/*/kernel/drivers/net

# Se eliminan apks conflictivas con gapps
rm -rf $REPACKOTA/system/app/Provision.apk
#rm -rf $REPACKOTA/system/app/QuickSearchBox.apk

# No se necesita recovery (en caso de existir)
rm -rf $REPACKOTA/recovery

# Strip modulos
if [ "$KERNELMOD" -eq 1 ];  then
    msgStatus "Comprimiendo módulos"
    find $REPACKOTA/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
fi

cd $REPACKOTA

if which 7za &>/dev/null
then
   msgStatus "Comprimiendo ROM usando 7za"
   7za a -tzip -mx9 -mmt $REPACK/update.zip .
else
   msgStatus "Comprimiendo ROM usando zip"
   zip $QUIET -r -9 $REPACK/update.zip . 
fi

firmar.sh $REPACK/update.zip $ROMPACKAGE
if [ "$?" -ne 0 ]; then
    msgErr "Error al obtener el fichero firmado $ROMPACKAGE"
    exit 1
fi

exit 0
