#!/system/bin/sh
RAMSIZE=`grep MemTotal /proc/meminfo | awk '{ print \$2 }'`
ZRAMSIZE=$(($RAMSIZE*100))

echo 1 > /sys/block/zram0/reset
echo $ZRAMSIZE > /sys/block/zram0/disksize
mkswap /dev/block/zram0
swapon /dev/block/zram0 
chmod 555 /etc/init.d/05zram
